### ISSUE TITLE
How do i use this on my nixos flake?

### ISSUE THREAD

**Issue by unchainedio** [jbotwell/nixaider#1]
Hi, thanks for your flake!  Im running a flake for my OS config on nixos.  I am using zaneyos a nixos custom flake configuration.

https://gitlab.com/Zaney/zaneyos

Does this build on top of your system flake? Does this make it like installing an app on nixos?

if im already running a nixos that was built via flakes.  Do i just git clone this repo into another directory and 

sudo nixos-rebuild switch --flake
?

please provide how you use it as  i really want to use aider on nixos and would appreciate any input you can provide

**Comment by jbotwell** [comment]
Hello. This is how I use it:
https://github.com/jbotwell/mynix/blob/main/modules/home-manager/aider.nix
which is through home manager.

But if you want to do it in your nixos config, it should look similar. Just with `environment.systemPackages` instead of `home.packages`. You could also use `nix run github:jbotwell/nixaider` and bind that to an alias if you like.

I hope that helps!

**Comment by jbotwell** [comment]
Also please see the top level flake file: https://github.com/jbotwell/mynix/blob/main/flake.nix for how I define inputs
